# Generated by Django 4.1.7 on 2023-04-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='age',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
