# Generated by Django 4.1.7 on 2023-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_model1_id_no_alter_model1_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='name',
        ),
        migrations.AddField(
            model_name='model1',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='image',
            field=models.ImageField(blank=True, upload_to='employee_images'),
        ),
        migrations.AddField(
            model_name='model1',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
