# Generated by Django 4.1.7 on 2023-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_model1_name_model1_date_of_birth_model1_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='registration_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
