# Generated by Django 4.1.7 on 2023-04-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_model1_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='Date_of_birth',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
