# Generated by Django 4.1.7 on 2023-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_model1_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='age',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
