# Generated by Django 4.1.7 on 2023-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_model1_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='Date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
