# Generated by Django 4.1.7 on 2023-04-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_model1_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='Date_of_birth',
        ),
    ]
