# Generated by Django 4.1.7 on 2023-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_model1_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
